version: "3"

services:
  stock-server:
    container_name: NODEJS_SERVER_STOCK
    build: "."
    volumes:
      - ./src:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - "9000:9000"
    networks:
      - customnet

  db:
    image: "mongo"
    container_name: MONGODB
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - customnet

networks:
  customnet:
    name: customnet
    driver: bridge
