version: '3.1'

services:
  server:
    container_name: NODEJS_SERVER
    build: '.'
    volumes:
      - ./src:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db:db
    ports:
      - '9000:9000'

  db:
    image: mysql
    container_name: MYSQL_SERVER
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock
    ports:
      - "3306:3306"
    volumes:
      - $HOME/projects/stock-management/mysql:/mysql